### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by ajorg-aws** [aws-samples/automated-incident-response-with-ssm#2]
This project has an MIT-0 [LICENSE](https://github.com/aws-samples/automated-incident-response-with-ssm/blob/master/LICENSE) but it also has [Apache-2.0 file headers](https://github.com/aws-samples/automated-incident-response-with-ssm/search?q=%22Apache+License%22&unscoped_q=%22Apache+License%22). Could you clean that up please?

**Comment by tzvetkov75** [comment]
Many thanks @ajorg-aws for notice. It is fixed.
